clear; clc; 
close all;
%cd("/if/research-gms/Chris/layoffs/")
%% Load in Data

hazard_panel = readtable("hazard_panel.csv");
hazard_average = readtable("hazard.csv");
hazard_srefmonA = readtable("hazard_srefmonA.csv");

%% new plot 
figure(1)

recall_PS = hazard_srefmonA(hazard_srefmonA.rwkesr2==4,:);
duration = recall_PS(recall_PS.srefmonA==1,:).duration;

pR1 = recall_PS(recall_PS.srefmonA==1,:).pR;
pR2 = recall_PS(recall_PS.srefmonA==2,:).pR;
pR3 = recall_PS(recall_PS.srefmonA==3,:).pR;
pR4 = recall_PS(recall_PS.srefmonA==4,:).pR;

subplot(2,2,1)
hold on
title('{(a) Exits employment for unemployment}','{after $4^{th}$ month of wave}','Interpreter','latex','FontSize',10)
plot(duration, pR1, '-ks', 'LineWidth', 2, 'MarkerSize', 8)
grid on;
xlabel("Elapsed months of unemployment", 'interpreter','Latex','FontSize',8);
xlim([0.5,8.5])
xticks([1:1:8]);
xtickangle(0);
yL =[0,0.05];
ylim(yL);
line([3.5,3.5],yL,'LineStyle',':','Color','Red','LineWidth',2)

subplot(2,2,2)
hold on;
title('{(b) Exits employment for unemployment}','{after $3^{rd}$ month of wave}','Interpreter','latex','FontSize',10)
plot(duration, pR4, '-ks', 'LineWidth', 2, 'MarkerSize', 8)
grid on;
xlabel("Elapsed months of unemployment", 'interpreter','Latex','FontSize',8);
xticks([1:1:8]);
xlim([0.5,8.5])
xtickangle(0);
yL =[0,0.05];
ylim(yL);
line([4.5,4.5],yL,'LineStyle',':','Color','Red','LineWidth',2)

subplot(2,2,3)
hold on;
title('{(c) Exits employment for unemployment}', '{after $2^{nd}$ month of wave}','Interpreter','latex','FontSize',10)
plot(duration, pR3, '-ks', 'LineWidth', 2, 'MarkerSize', 8)
grid on;
xlim([0.5,8.5])
xlabel("Elapsed months of unemployment", 'interpreter','Latex','FontSize',8);
xticks([1:1:8]);
xtickangle(0);
yL =[0,0.05];
ylim(yL);
line([5.5,5.5],yL,'LineStyle',':','Color','Red','LineWidth',2)

subplot(2,2,4)
hold on;
title('{(d) Exits employment for unemployment}', '{after $1^{st}$ month of wave}','Interpreter','latex','FontSize',10)
plot(duration, pR2, '-ks', 'LineWidth', 2, 'MarkerSize', 8)
grid on;
xlabel("Elapsed months of unemployment", 'interpreter','Latex','FontSize',8);
xlim([0.5,8.5])
xticks([1:1:8]);
xtickangle(0);
yL =[0,0.05];
ylim(yL);
line([6.5,6.5],yL,'LineStyle',':','Color','Red','LineWidth',2)

set(gcf,'Units','inches');
set(gcf,'Position',[0 0 8 5])
screenposition = get(gcf,'Position');
set(gcf,...
    'PaperPosition',[0 0 screenposition(3:4)],...
      'PaperSize',[screenposition(3:4)]);
yL=get(gca,'Ylim');
print('-dpdf','-painters','./figures/PSrecall')

%% Plotting Figures

opt.rwkesr2 = {3,4,3,4,3,4}; % 3 or 4 
opt.prob_col = {'pE','pE','pR','pR','pN','pN'}; % pR, pN, pE
opt.lgnd = {0,0,0,0,0,1};
opt.title_name = { ...
  'A. Temporary layoff: Exit to any employment', 'D. Permanent separation: Exit to any employment' ...
  'B. Temporary layoff: Exit to recall', 'E.  Permanent Separation: Exit to recall', ... 
  'C. Temporary layoff: Exit to new job', 'F. Permanent separation: Exit to new job', ...
  };

figure('Position',[0 0 1000 1400],'PaperPositionMode','Auto','DefaultAxesFontSize',15);
hold on;
clf;
for ii=1:6
  subplot(3,2,ii)
  hold on;
  if (ii<3) 
    ylim([0,0.8])
  else
    ylim([0,0.6])
  end
  yL = ylim;
  if (ii==4 | ii==6)
    line([3.5,3.5],yL,'LineStyle',':','Color','Red','LineWidth',2)
  end
  figures.wave_probability_histogram(hazard_panel, hazard_average, opt.rwkesr2{ii}, opt.prob_col{ii}, opt.title_name{ii},opt.lgnd{ii})
end



figure_property.units = 'inches';
figure_property.format = 'pdf';
figure_property.Preview= 'none';
figure_property.Width= '9'; % Figure height on canvas
figure_property.Height= '11'; % Figure width on canvas
figure_property.Units= 'inches';
figure_property.Color= 'rgb';
figure_property.Background= 'w';
figure_property.FixedfontSize= '12';
figure_property.ScaledfontSize= 'auto';
figure_property.FontMode= 'scaled';
figure_property.FontSizeMin= '12';
figure_property.FixedLineWidth= '1';
figure_property.ScaledLineWidth= 'auto';
figure_property.LineMode= 'none';
figure_property.LineWidthMin= '0.1';
figure_property.FontWeight= 'auto';
figure_property.FontAngle= 'auto';
figure_property.PSLevel= '3';
figure_property.Renderer= 'painters';
figure_property.Resolution= '600';
figure_property.LineStyleMap= 'none';
figure_property.ApplyStyle= '0';
figure_property.Bounds= 'tight';
figure_property.LockAxes= 'off';
figure_property.LockAxesTicks= 'off';
figure_property.ShowUI= 'off';
figure_property.SeparateText= 'off';

set(gcf,'PaperUnits','inches');
set(gcf,'PaperPositionMode','auto');
set(gcf, 'PaperOrientation', 'portrait')
set(gcf,'PaperSize',[str2num(figure_property.Width) str2num(figure_property.Height)]); % Canvas Size
set(gcf,'Units','inches');
hgexport(gcf,'figures/exit_hazards.pdf',figure_property); %Set desired file name
% set(gcf, "PaperPosition", [0,0,1900,900])
% print('-dpdf', gcf, join(['figures/','all']));
%%

%landscape

opt.rwkesr2 = {3,3,3,4,4,4}; % 3 or 4 
opt.prob_col = {'pE','pR','pN','pE','pR','pN'}; % pR, pN, pE
opt.lgnd = {0,0,0,0,0,1};
%opt.title_name = {'(A) TL: Exit to recall', '(B) TL: Exit to new job', ... 
%  '(C) TL: Exit to any employment', '(D) PS: Exit to recall', '(E) PS: Exit to new job', ...
%  '(F) PS: Exit to any employment'};
opt.title_name = { ...
  'A. Temporary layoff: Exit to any employment', ...
  'B. Temporary layoff: Exit to recall', ...
  'C. Temporary layoff: Exit to new job', ...
  'D. Permanent separation: Exit to any employment' ...
  'E.  Permanent Separation: Exit to recall', ... 
  'F. Permanent separation: Exit to new job', ...
  };

figure('Position',[0 0 1400 1000],'PaperPositionMode','Auto','DefaultAxesFontSize',15);
hold on;
clf;
for ii=1:6
  subplot(2,3,ii)
  hold on;
  if (ii==6 | ii==7 | ii==4 | ii==5)
    ylim([0,0.6])
  else
    ylim([0,0.8])
  end
  if (ii==5 | ii==6)
    line([3.5,3.5],yL,'LineStyle',':','Color','Red','LineWidth',2)
  end
  figures.wave_probability_histogram(hazard_panel, hazard_average, opt.rwkesr2{ii}, opt.prob_col{ii}, opt.title_name{ii},opt.lgnd{ii})
end

figure_property.units = 'inches';
figure_property.format = 'pdf';
figure_property.Preview= 'none';
figure_property.Width= '16'; % Figure height on canvas
figure_property.Height= '10'; % Figure width on canvas
figure_property.Units= 'inches';
figure_property.Color= 'rgb';
figure_property.Background= 'w';
figure_property.FixedfontSize= '12';
figure_property.ScaledfontSize= 'auto';
figure_property.FontMode= 'scaled';
figure_property.FontSizeMin= '12';
figure_property.FixedLineWidth= '1';
figure_property.ScaledLineWidth= 'auto';
figure_property.LineMode= 'none';
figure_property.LineWidthMin= '0.1';
figure_property.FontWeight= 'auto';
figure_property.FontAngle= 'auto';
figure_property.PSLevel= '3';
figure_property.Renderer= 'painters';
figure_property.Resolution= '600';
figure_property.LineStyleMap= 'none';
figure_property.ApplyStyle= '0';
figure_property.Bounds= 'tight';
figure_property.LockAxes= 'off';
figure_property.LockAxesTicks= 'off';
figure_property.ShowUI= 'off';
figure_property.SeparateText= 'off';

set(gcf,'PaperUnits','inches');
set(gcf,'PaperPositionMode','auto');
set(gcf, 'PaperOrientation', 'landscape')
set(gcf,'PaperSize',[str2num(figure_property.Width) str2num(figure_property.Height)]); % Canvas Size
set(gcf,'Units','inches');
hgexport(gcf,'figures/exit_hazards_landscape.pdf',figure_property); %Set desired file name


%%%

opt.srefmonA = {0,1,2,3,4,0,1,2,3,4,0,1,2,3,4}; % 3 or 4 
opt.prob_col = {'pR','pR','pR','pR','pR','pN','pN','pN','pN','pN','pE','pE','pE','pE','pE'}; % pE, pR, pN

figure('Position',[0 0 1900 900],'PaperPositionMode','Auto','DefaultAxesFontSize',17);
clf
for ii=1:15
  subplot (3,5,ii)
  figures.this(hazard_srefmonA,hazard_average, 3, opt.srefmonA{ii},opt.prob_col{ii}, '')  
  if (ii<=5)
    yL = [0, 0.8]
    ylim(yL);
    yticks([0:.2:.8])
  elseif (ii>5 & ii<11)
    yL = [0,0.75];
    ylim(yL);
    yticks([0:.2:.6])
  else
    yL = [0, 1.00]
    ylim(yL);
    yticks([0:.25:1.0])
  end
  if (opt.srefmonA{ii}>0)
    line([5-opt.srefmonA{ii},5-opt.srefmonA{ii}],yL,'LineStyle',':','Color','Red','LineWidth',2)
    line([9-opt.srefmonA{ii},9-opt.srefmonA{ii}],yL,'LineStyle',':','Color','Red','LineWidth',2)
  end
end

figure_property.Width= '16'; % Figure width on canvas
figure_property.Height= '9'; % Figure height on canvas

annotation(gcf,'textbox',...
    [0.0554276315789479 0.808888888888889 0.0540460526315786 0.0299580607926083],...
    'String',{'(\textit{1})' 'Recalls'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.0526315789473686 0.511111111111111 0.0642105263157901 0.0325667564447814],...
    'String',{'(\textit{2})' 'New jobs'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.0542105263157897 0.22 0.0636842105263162 0.0359483989568587],...
    'String',{'(\textit{3})' 'Recalls','+ New jobs'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.162593201754388 0.938888888888889 0.0426699561403499 0.0293783506476805],...
    'String',{'(\textit{a}) All'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.29686951754386 0.93 0.105246710526315 0.0502479158650757],...
    'String',{'(\textit{b}) 1st reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.453684210526316 0.93 0.121578947368421 0.0502479158650757],...
    'String',{'(\textit{c}) 2nd reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(gcf,'textbox',...
    [0.611578947368421 0.93 0.123157894736842 0.0502479158650759],...
    'String',{'(\textit{d}) 3rd reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(gcf,'textbox',...
    [0.776315789473686 0.93 0.122631578947369 0.0502479158650757],...
    'String',{'(\textit{e}) 4th reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

set(gcf,'PaperUnits','inches');
set(gcf,'PaperPositionMode','auto');
set(gcf, 'PaperOrientation', 'landscape')
set(gcf,'PaperSize',[str2num(figure_property.Width) str2num(figure_property.Height)]); % Canvas Size
set(gcf,'Units','inches');

hgexport(gcf,'figures/TL.pdf',figure_property); %Set desired file name
%%


figure('Position',[0 0 1900 900],'PaperPositionMode','Auto','DefaultAxesFontSize',17);
clf
for ii=1:15
  subplot (3,5,ii)
  figures.this(hazard_srefmonA,hazard_average, 4, opt.srefmonA{ii},opt.prob_col{ii}, '')  
  if (ii<=5)
    yL = [0,0.08]
    ylim(yL);
    yticks([0:.02:.08])
  elseif (ii>5 & ii<11)
    yL = [0,0.75];
    ylim(yL);
    yticks([0:.25:1])
  else
    yL = [0, 0.75]
    ylim(yL);
    yticks([0:.25:.75])
  end
  if (opt.srefmonA{ii}>0)
    line([5-opt.srefmonA{ii},5-opt.srefmonA{ii}],yL,'LineStyle',':','Color','Red','LineWidth',2)
    line([9-opt.srefmonA{ii},9-opt.srefmonA{ii}],yL,'LineStyle',':','Color','Red','LineWidth',2)
  end
end

figure_property.Width= '16'; % Figure width on canvas
figure_property.Height= '9'; % Figure height on canvas


annotation(gcf,'textbox',...
    [0.0554276315789479 0.808888888888889 0.0540460526315786 0.0299580607926083],...
    'String',{'(\textit{1})' 'Recalls'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.0526315789473686 0.511111111111111 0.0642105263157901 0.0325667564447814],...
    'String',{'(\textit{2})' 'New jobs'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.0542105263157897 0.22 0.0636842105263162 0.0359483989568587],...
    'String',{'(\textit{3})' 'Recalls','+ New jobs'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.162593201754388 0.938888888888889 0.0426699561403499 0.0293783506476805],...
    'String',{'(\textit{a}) All'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.29686951754386 0.93 0.105246710526315 0.0502479158650757],...
    'String',{'(\textit{b}) 1st reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(gcf,'textbox',...
    [0.453684210526316 0.93 0.121578947368421 0.0502479158650757],...
    'String',{'(\textit{c}) 2nd reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(gcf,'textbox',...
    [0.611578947368421 0.93 0.123157894736842 0.0502479158650759],...
    'String',{'(\textit{d}) 3rd reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(gcf,'textbox',...
    [0.776315789473686 0.93 0.122631578947369 0.0502479158650757],...
    'String',{'(\textit{e}) 4th reference','month'},...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',17,...
    'FontName','SansSerif',...
    'FitBoxToText','off',...
    'EdgeColor','none');


set(gcf,'PaperUnits','inches');
set(gcf,'PaperPositionMode','auto');
set(gcf, 'PaperOrientation', 'landscape')
set(gcf,'PaperSize',[str2num(figure_property.Width) str2num(figure_property.Height)]); % Canvas Size
set(gcf,'Units','inches');

hgexport(gcf,'figures/PS.pdf',figure_property); %Set desired file name

